### ISSUE TITLE
Kanban Board Project

### ISSUE THREAD

**Issue by Wils-FOURR-speed** [sheezu900/Ruby_capston_project#5]
### Description:
- Link to the project here: [Ruby-Capstone-Project](https://github.com/sheezu900/Ruby_capston_project/projects/1)
- A team of 3 people.
- `Team member #1` assigned to [Wils-FOURR-speed](https://github.com/Wils-FOURR-speed)
- `Team member #2` assigned to [Akorede](https://github.com/Akorede3133)
- `Team member #2` assigned to [Shah-Zaman](https://github.com/sheezu900)

**Comment by divinecharlotte** [comment]
Hi  @Team    , 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## To Highlight 💯 

- Clean code👍 
- Implemented some project requirements   👍 

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)
## Required Changes ♻️

- [ ] kindly consider following the below requirement while sharing cards to meet the project requirement because currently your cards are very congested and summarized and each card might take a long to be done 👇 
>  Each `task` should be a separate card that:
Has a descriptive title.
Has the number of points in the [Xpt] prefix. That number should indicate the number of points that show how complex the task is. 1 point = 1 hour of estimated work. You shouldn't change the points after dividing up cards, even if the actual work takes longer.
Has a description of the task.

_Check the comments under the review._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by julie-ify** [comment]
## Hi @Wils-FOURR-speed, @sheezu900 and @Akorede3133,

Good job so far!

## Highlights!
- Good code organization and descriptive tasks ✔️
- Descriptive README ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
- [ ] You assigned this task to all team members instead of the third team member. Kindly fix that.

  ![image](https://github.com/sheezu900/Ruby_capston_project/assets/81468675/d6c070ee-30db-4ea5-871f-b77ad473832d)

- [ ] Team member 3 needs to split [this task](https://github.com/sheezu900/Ruby_capston_project/issues/25) into more than one. As highlighted by the previous reviewer, the tasks should not be congested.

  ![image](https://github.com/sheezu900/Ruby_capston_project/assets/81468675/cfffd680-d6ce-4efc-8d16-de29881aab3c)

- [ ] These two tasks are duplicates of each other. Kindly remove one.

  ![image](https://github.com/sheezu900/Ruby_capston_project/assets/81468675/fef11da2-cbbc-4dd0-83b3-1fd4be8ea010)

- [ ] Team member 1 has 20 points, member 2 has 26 and member 3 has 28 points. Kindly note that no team member's point should surpass the other member's point with a number equal to or greater than 5 points. The highest difference between any two team members should be 4. Kindly reassign your points.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by julie-ify** [comment]
Hi @Wils-FOURR-speed, @sheezu900 and @Akorede3133,

## Highlights!
- Descriptive issue ✔️
- Descriptive tasks ✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
